// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqBpSqZ6q-uhZhCJ5fEPVRGYtCe59QMc',
    appId: '1:961667427724:android:abec476f5fe39c3fbd3aa9',
    messagingSenderId: '961667427724',
    projectId: 'booki-d372e',
    storageBucket: 'booki-d372e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWXRig06qrnYpJrJjzhDQVPKuYfrA4NSM',
    appId: '1:961667427724:ios:ade3e86d3ff1426dbd3aa9',
    messagingSenderId: '961667427724',
    projectId: 'booki-d372e',
    storageBucket: 'booki-d372e.firebasestorage.app',
    iosBundleId: 'com.example.booki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWXRig06qrnYpJrJjzhDQVPKuYfrA4NSM',
    appId: '1:961667427724:ios:ade3e86d3ff1426dbd3aa9',
    messagingSenderId: '961667427724',
    projectId: 'booki-d372e',
    storageBucket: 'booki-d372e.firebasestorage.app',
    iosBundleId: 'com.example.booki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5TcV4EuCllgOboovStGYkd4pMWbsfxTw',
    appId: '1:961667427724:web:64aeb324de22ea69bd3aa9',
    messagingSenderId: '961667427724',
    projectId: 'booki-d372e',
    authDomain: 'booki-d372e.firebaseapp.com',
    storageBucket: 'booki-d372e.firebasestorage.app',
    measurementId: 'G-9RY553E4KW',
  );
}
